build system corrections

diff --git a/tests/async/makefile b/tests/async/makefile
--- a/tests/async/makefile
+++ b/tests/async/makefile
@@ -4,18 +4,18 @@ this_name := tests
 
 this_cxxflags += -g
 this_cxxflags += -Wall
-this_cxxflags += -Wno-format #no warnings about format
-this_cxxflags += -Wno-format-security #no warnings about format
+this_cxxflags += -Wno-format
+this_cxxflags += -Wno-format-security
 this_cxxflags += -DDEBUG
-this_cxxflags += -fstrict-aliasing #strict aliasing!!!
+this_cxxflags += -fstrict-aliasing
 this_cxxflags += -std=c++11
 
 this_srcs += main.cpp
 
-this_ldlibs += -lsvgdom $(d)../../src/libsvgren$(soext) -lpapki `pkg-config --libs cairo` -lpng -lstdc++ -lpthread
+this_ldlibs += -lsvgdom $(d)../../src/build/libsvgren$(dot_so) -lpapki `pkg-config --libs cairo` -lpng -lstdc++ -lpthread
 
 ifeq ($(os), macosx)
-    this_cxxflags += -stdlib=libc++ #this is needed to be able to use c++11 std lib
+    this_cxxflags += -stdlib=libc++ # this is needed to be able to use c++11 std lib
     this_ldlibs += -lc++
 else ifeq ($(os),windows)
 endif
@@ -31,17 +31,17 @@ this_svgs := $(shell ls $(d)../samples/testdata/*.svg)
 
 define this_rules
 test:: $(prorab_this_name)
-	@myci-running-test.sh $(this_test)
-	$(prorab_echo)cp $(d)../../src/*.dll . || true
-	$(prorab_echo)LD_LIBRARY_PATH=$(d)../../src DYLD_LIBRARY_PATH=$$$$LD_LIBRARY_PATH $(d)./tests $(this_svgs); \
-		if [ $$$$? -ne 0 ]; then myci-error.sh "test failed"; exit 1; fi
-	@myci-passed.sh
+$(.RECIPEPREFIX)@myci-running-test.sh $(this_test)
+$(.RECIPEPREFIX)$(a)cp $(d)../../src/build/*.dll . || true
+$(.RECIPEPREFIX)$(a)LD_LIBRARY_PATH=$(d)../../src/build DYLD_LIBRARY_PATH=$$$$LD_LIBRARY_PATH $(d)./tests $(this_svgs); \
+        if [ $$$$? -ne 0 ]; then myci-error.sh "test failed"; exit 1; fi
+$(.RECIPEPREFIX)@myci-passed.sh
 endef
-#NOTE: this test is turned off because there is some problem with it when running under qemu (raspberry pi) on CI machine
+# TODO: enable test
+# NOTE: this test is turned off because there is some problem with it when running under qemu (raspberry pi) on CI machine
 #$(eval $(this_rules))
 
+# add dependency on libsvgren
+$(prorab_this_name): $(abspath $(d)../../src/build/libsvgren$(dot_so))
 
-#add dependency on libsvgren
-$(prorab_this_name): $(abspath $(d)../../src/libsvgren$(soext))
-
-$(eval $(call prorab-try-include,$(d)../../src/makefile))
+$(eval $(call prorab-include, ../../src/makefile))
diff --git a/tests/render_dims/makefile b/tests/render_dims/makefile
--- a/tests/render_dims/makefile
+++ b/tests/render_dims/makefile
@@ -4,19 +4,19 @@ this_name := tests
 
 this_cxxflags += -g
 this_cxxflags += -Wall
-this_cxxflags += -Wno-format #no warnings about format
-this_cxxflags += -Wno-format-security #no warnings about format
+this_cxxflags += -Wno-format
+this_cxxflags += -Wno-format-security
 this_cxxflags += -DDEBUG
-this_cxxflags += -fstrict-aliasing #strict aliasing!!!
+this_cxxflags += -fstrict-aliasing
 this_cxxflags += -std=c++11
 
 this_srcs += main.cpp
 
-this_ldlibs += -lsvgdom $(d)../../src/libsvgren$(soext) -lpapki `pkg-config --libs cairo` -lstdc++
+this_ldlibs += -lsvgdom $(d)../../src/build/libsvgren$(dot_so) -lpapki `pkg-config --libs cairo` -lstdc++
 this_ldflags += -L$(d)../../src
 
 ifeq ($(os), macosx)
-    this_cxxflags += -stdlib=libc++ #this is needed to be able to use c++11 std lib
+    this_cxxflags += -stdlib=libc++ # this is needed to be able to use c++11 std lib
     this_ldlibs += -lc++
 else ifeq ($(os),windows)
 else
@@ -27,21 +27,20 @@ this_no_install := true
 
 $(eval $(prorab-build-app))
 
-
 this_dirs := $(subst /, ,$(d))
 this_test := $(word $(words $(this_dirs)),$(this_dirs))
 
 define this_rules
 test:: $(prorab_this_name)
-	@myci-running-test.sh $(this_test)
-	$(prorab_echo)cp $(d)../../src/*.dll $(d) || true
-	$(prorab_echo)(cd $(d) && LD_LIBRARY_PATH=../../src DYLD_LIBRARY_PATH=$$$$LD_LIBRARY_PATH ./tests); \
-		if [ $$$$? -ne 0 ]; then myci-error.sh "test failed"; exit 1; fi
-	@myci-passed.sh
+$(.RECIPEPREFIX)@myci-running-test.sh $(this_test)
+$(.RECIPEPREFIX)$(a)cp $(d)../../src/build/*.dll $(d) || true
+$(.RECIPEPREFIX)$(a)(cd $(d) && LD_LIBRARY_PATH=../../src/build DYLD_LIBRARY_PATH=$$$$LD_LIBRARY_PATH ./tests); \
+        if [ $$$$? -ne 0 ]; then myci-error.sh "test failed"; exit 1; fi
+$(.RECIPEPREFIX)@myci-passed.sh
 endef
 $(eval $(this_rules))
 
-#add dependency on libsvgren
-$(prorab_this_name): $(abspath $(d)../../src/libsvgren$(soext))
+# add dependency on libsvgren
+$(prorab_this_name): $(abspath $(d)../../src/build/libsvgren$(dot_so))
 
-$(eval $(call prorab-try-include,$(d)../../src/makefile))
+$(eval $(call prorab-include, ../../src/makefile))
