render dimensions test added

diff --git a/tests/renderDim/makefile b/tests/renderDim/makefile
--- a/tests/renderDim/makefile
+++ b/tests/renderDim/makefile
@@ -1,6 +1,6 @@
 include prorab.mk
 
-this_name := checksvg
+this_name := tests
 
 this_cxxflags += -g
 this_cxxflags += -Wall
@@ -9,20 +9,22 @@ this_cxxflags += -DDEBUG
 this_cxxflags += -fstrict-aliasing #strict aliasing!!!
 this_cxxflags += -std=c++11
 
-this_srcs += checksvg.cpp
+this_srcs += main.cpp
 
-this_ldlibs += -lsvgdom $(d)../../src/libsvgren$(soext) -lpapki `pkg-config --libs cairo` -lpng -lstdc++
+this_ldlibs += -lsvgdom $(d)../../src/libsvgren$(soext) -lpapki `pkg-config --libs cairo` -lstdc++
+this_ldflags += -L$(d)../../src
 
 ifeq ($(os), macosx)
     this_cxxflags += -stdlib=libc++ #this is needed to be able to use c++11 std lib
     this_ldlibs += -lc++
 else ifeq ($(os),windows)
     this_ldlibs += -lpugixml
+else
+    this_ldlibs += -lX11
 endif
 
 $(eval $(prorab-build-app))
 
-this_svgs := $(patsubst %.svg,%,$(shell ls $(d)testdata/*.svg))
 
 this_dirs := $(subst /, ,$(d))
 this_test := $(word $(words $(this_dirs)),$(this_dirs))
@@ -30,16 +32,12 @@ this_test := $(word $(words $(this_dirs)),$(this_dirs))
 define this_rules
 test:: $(prorab_this_name)
 	@prorab-running-test.sh $(this_test)
-	$(prorab_echo)cp $(d)../../src/*.dll . || true
-	$(prorab_echo)for f in $(this_svgs); do \
-	    echo "checking file $$$$f.svg..." && \
-	    LD_LIBRARY_PATH=$(d)../../src $(d)./checksvg $$$$f.svg $$$$f.png; \
-	    if [ $$$$? -ne 0 ]; then prorab-error.sh "rendered SVG did not match etalon sample"; exit 1; fi \
-	done
+	$(prorab_echo)cp $(d)../../src/*.dll $(d) || true
+	$(prorab_echo)LD_LIBRARY_PATH=$(d)../../src DYLD_LIBRARY_PATH=$$$$LD_LIBRARY_PATH $(d)./tests; \
+		if [ $$$$? -ne 0 ]; then prorab-error.sh "test failed"; exit 1; fi
 	@prorab-passed.sh
 endef
 $(eval $(this_rules))
-
 
 #add dependency on libsvgren
 $(prorab_this_name): $(abspath $(d)../../src/libsvgren$(soext))
