updating build scripts

diff --git a/tests/renderDim/makefile b/tests/renderDim/makefile
--- a/tests/renderDim/makefile
+++ b/tests/renderDim/makefile
@@ -32,11 +32,11 @@ this_test := $(word $(words $(this_dirs)),$(this_dirs))
 
 define this_rules
 test:: $(prorab_this_name)
-	@prorab-running-test.sh $(this_test)
+	@myci-running-test.sh $(this_test)
 	$(prorab_echo)cp $(d)../../src/*.dll $(d) || true
 	$(prorab_echo)(cd $(d) && LD_LIBRARY_PATH=../../src DYLD_LIBRARY_PATH=$$$$LD_LIBRARY_PATH ./tests); \
-		if [ $$$$? -ne 0 ]; then prorab-error.sh "test failed"; exit 1; fi
-	@prorab-passed.sh
+		if [ $$$$? -ne 0 ]; then myci-error.sh "test failed"; exit 1; fi
+	@myci-passed.sh
 endef
 $(eval $(this_rules))
 
